#!/bin/bash

while true; do
    
    BATTINFO=`acpi -b`
    if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:15:00 ]] ; then
        DISPLAY=:0.0 /usr/bin/notify-send "Low battery\!" "$BATTINFO"
    fi
    
    sleep 60
    
done
