#!/bin/bash

# Required packages:
#   dunst
#
# Description:
#   Shows a dunst notification to show the
#   volume or brightness with a progress bar
#
# Usage:
#   notif-prog-bar <vol|bright>

if [[ "$1" == "vol" ]]; then
    SINK_NAME=$(pacmd stat | awk -F": " '/^Default sink name: /{print $2}')
    VOL=$(pacmd list-sinks |
        awk '/^\s+name: /{indefault = $2 == "<'$SINK_NAME'>"}
            /^\s+volume: / && indefault {print $5; exit}' |
        awk -F"%" '{print $1}')
    dunstify -u low -h string:x-canonical-private-synchronous:volume "Volume: " -h int:value:"$VOL"
elif [[ "$1" == "bright" ]]; then
    BRIGHT="$(xbacklight)"
    dunstify -u low -h string:x-canonical-private-synchronous:brightness "Brightness: " -h int:value:"$BRIGHT"
else
    echo "'$1'" is not a valid option.
fi

